[workspace]
resolver = "3"
members = ["crates/*", "sandbox"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
approx = "0.5"
bytemuck = "1.25"
env_logger = "0.11"
glam = { version = "0.33", features = ["bytemuck"] }
log = { version = "0.4", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
pollster = "1"
rustc-hash = "2"
thiserror = "2"
wgpu = "30"
winit = "0.30"

vivid-core = { path = "./crates/vivid-core/" }
vivid-platform = { path = "./crates/vivid-platform/" }
vivid-render = { path = "./crates/vivid-render/" }

[workspace.lints.rust]
unsafe_code = "deny"
rust_2018_idioms = { level = "warn", priority = -1 }
unused_qualifications = "warn"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
similar_names = "allow"

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
