[package]
name = "vivid-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
log.workspace = true
pollster.workspace = true
thiserror.workspace = true
wgpu.workspace = true

vivid-core.workspace = true

[dev-dependencies]
approx.workspace = true

[lints]
workspace = true
